DROP DATABASE IF EXISTS minerva;
CREATE DATABASE minerva WITH ENCODING 'UTF8';

\c minerva;

CREATE TABLE MESSAGES(
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    text TEXT,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE USER server;
ALTER USER server WITH PASSWORD '';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to server;